### ISSUE TITLE
tanya

### ISSUE THREAD

**Issue by emonkz** [FndNur1Labs/WayangGUI#23]
Halo gan mau tanya donk soal cryptonight coin, soal buat wallet bisa info nggak tutorialnya gimana langkah2nya.

Untuk tutorial detail cara buat walletnya gimana ya gan? udah berhasil buat coinnya, poolnya, explorernya, cuma berminggu2 masih belum ketemu tutorial lengkap cara buat walletnya euy. Bisa request tutorial detailnya gan?

**Comment by FndNur1Labs** [comment]
Gampang itu. Tinggal git submodule init && git update --remote

**Comment by FndNur1Labs** [comment]
Terus make. Ntar saya buat.

**Comment by emonkz** [comment]
gimana2 gan? masih nggak mudeng langkahnya.

yg git submodule add https:github.com/blablablabla cryptonote itu kan?

terus make.


Nah kalo wallet untuk windowsnya gimana?

**Comment by emonkz** [comment]
ato mungkin maksudnya, build walletnyanya di linux, nanti walletnya bisa compatible juga di windows, gitu ya?

**Comment by FndNur1Labs** [comment]
Build windows di wiki cryptonote evo

**Comment by emonkz** [comment]
yang ini https://github.com/FndNur1Labs/CryptonoteEvo/wiki ?

tutorialnya dimananya?

**Comment by FndNur1Labs** [comment]
Homdx tutor.

**Comment by megarootz** [comment]
FnNur1Labs saya mau tanya, bagaimana mau fix ini yaa?

megaroot@megaroot:~/xcredit$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The CXX compiler identification is unknown
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:112 (find_package)


-- Found Git: /usr/bin/git
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- Could NOT find Threads (missing:  Threads_FOUND) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/megaroot/xcredit
   used as include directory in directory /home/megaroot/xcredit/external/miniupnpc
   used as include directory in directory /home/megaroot/xcredit/external/gtest
   used as include directory in directory /home/megaroot/xcredit/external/gtest
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/src
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests
   used as include directory in directory /home/megaroot/xcredit/tests

-- Configuring incomplete, errors occurred!
See also "/home/megaroot/xcredit/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/megaroot/xcredit/build/release/CMakeFiles/CMakeError.log".
make: *** [cmake-release] Error 1
megaroot@megaroot:~/xcredit$ 

pls help me  :'(

**Comment by FndNur1Labs** [comment]
apt install build-essential libqt4-dev qt5-qmake cmake qttools5-dev
libqt5webkit5-dev qttools5-dev-tools qt5-default python-sphinx
texlive-latex-base inotify-tools openssl libssl-dev libdb++-dev
libminiupnpc-dev git sqlite3 libsqlite3-dev g++ libpng-dev gedit python gcc
make libbz2-dev libdb-dev libssl-dev libreadline-dev autoconf libtool
libleveldb-dev libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
automake nano qtbase5-dev qt4-dev-tools libncurses5-dev fakeroot wget bzip2
bison flex dctrl-tools libelf-dev libuv1-dev libmicrohttpd-dev pkg-config
libevent-dev libunbound-dev libminiupnpc-dev libunwind8-dev libldns-dev
libexpat1-dev doxygen graphviz screen libdb{,++}-dev libzmq3-dev

**Comment by megarootz** [comment]
thnks kamu asal indon yaa?

**Comment by megarootz** [comment]
[100%] Building CXX object tests/CMakeFiles/TransfersTests.dir/TransfersTests/TestTxPoolSync.cpp.o
[100%] Linking CXX executable transfers_tests
/home/megaroot/xcredit/src/CryptoNoteCore/BlockIndex.cpp: In member function ‘buildSparseChain’:
/home/megaroot/xcredit/src/CryptoNoteCore/BlockIndex.cpp:51:66: warning: ‘startBlockHeight’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     size_t sparseChainEnd = static_cast<size_t>(startBlockHeight + 1);
                                                                  ^
/home/megaroot/xcredit/src/CryptoNoteCore/BlockIndex.cpp:47:14: note: ‘startBlockHeight’ was declared here
     uint32_t startBlockHeight;
              ^
/home/megaroot/xcredit/src/CryptoNoteCore/Blockchain.cpp: In member function ‘findBlockchainSupplement’:
/home/megaroot/xcredit/src/CryptoNoteCore/Blockchain.cpp:1228:10: warning: ‘blockIndex’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return blockIndex;
          ^
/home/megaroot/xcredit/src/CryptoNoteCore/Blockchain.cpp:1225:12: note: ‘blockIndex’ was declared here
   uint32_t blockIndex;
            ^
make[3]: Leaving directory '/home/megaroot/xcredit/build/release'
[100%] Built target TransfersTests
make[2]: Leaving directory '/home/megaroot/xcredit/build/release'
make[1]: Leaving directory '/home/megaroot/xcredit/build/release'
megaroot@megaroot:~/xcredit$ 


ini apa silapnya yaa

**Comment by FndNur1Labs** [comment]
pake v1 ada PoS juga sama ico. disable ico juga bisa

**Comment by FndNur1Labs** [comment]
yep asli indonesia temen saya luar~

**Comment by megarootz** [comment]
bagaimana ya mau fix itu ,lco apa ya bang, saya kurang mahir ,, bru mau
belajar..

**Comment by FndNur1Labs** [comment]
disini aja reponya lengkap!

https://github.com/orgs/Nur1Labs/teams/cryptonoteevo-development

**Comment by FndNur1Labs** [comment]
jangan pake yang lama udah yang baru lebih compitable dengan anti-asic dan
juga master nodes

**Comment by megarootz** [comment]
boleh kasi link yg baru punya, pls

**Comment by FndNur1Labs** [comment]
https://github.com/CatalystCash/CatalystGUI
